# One-shot generator for the culture JSON files. Run once; the emitted
# files are the source of truth (edit them directly afterwards).
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "cultures"
compounds = json.load(open(OUT.parent / "compound_atoms.json", encoding="utf-8"))

# ---------------------------------------------------------------- German
de = {
    "culture": "de",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["."],
        "ordinalWords": {
            "erste": 1, "zweite": 2, "dritte": 3, "vierte": 4, "fünfte": 5,
            "sechste": 6, "siebte": 7, "achte": 8, "neunte": 9, "zehnte": 10,
            "elfte": 11, "zwölfte": 12, "zwanzigste": 20,
        },
        "atoms": {
            "null": 0, "eins": 1, "zwei": 2, "drei": 3, "vier": 4, "fünf": 5,
            "sechs": 6, "sieben": 7, "acht": 8, "neun": 9, "zehn": 10,
            "elf": 11, "zwölf": 12, "dreizehn": 13, "vierzehn": 14, "fünfzehn": 15,
            "sechzehn": 16, "siebzehn": 17, "achtzehn": 18, "neunzehn": 19,
            "zwanzig": 20, "dreißig": 30, "vierzig": 40, "fünfzig": 50,
            "sechzig": 60, "siebzig": 70, "achtzig": 80, "neunzig": 90,
            **compounds["de"],
        },
        "scales": {"hundert": 100, "tausend": 1000, "million": 1000000, "millionen": 1000000,
                    "milliarde": 1000000000, "milliarden": 1000000000},
        "connectors": [],
        "negativeWords": ["minus"],
    },
    "percentage": {"suffixes": ["%", "prozent"], "prefixes": []},
    "dimension": [
        {"canonical": "Meter", "base": "Meter", "factor": 1.0, "patterns": ["m", "meter"]},
        {"canonical": "Kilometer", "base": "Meter", "factor": 1000.0, "patterns": ["km", "kilometer", "kilometern"]},
        {"canonical": "Centimeter", "base": "Meter", "factor": 0.01, "patterns": ["cm", "zentimeter", "zentimetern"]},
        {"canonical": "Millimeter", "base": "Meter", "factor": 0.001, "patterns": ["mm", "millimeter", "millimetern"]},
        {"canonical": "Meile", "base": "Meter", "factor": 1609.344, "patterns": ["meile", "meilen"]},
        {"canonical": "Kilogramm", "base": "Kilogramm", "factor": 1.0, "patterns": ["kg", "kilogramm", "kilogrammen"]},
        {"canonical": "Gramm", "base": "Kilogramm", "factor": 0.001, "patterns": ["g", "gramm", "grammen"]},
        {"canonical": "Milligramm", "base": "Kilogramm", "factor": 1e-06, "patterns": ["mg", "milligramm"]},
        {"canonical": "Pfund", "base": "Kilogramm", "factor": 0.45359237, "patterns": ["pfund"]},
        {"canonical": "Quadratmeter", "base": "SquareMeter_de", "factor": 1.0, "patterns": ["m2", "m²", "quadratmeter"]},
        {"canonical": "Quadratkilometer", "base": "SquareMeter_de", "factor": 1000000.0, "patterns": ["km2", "km²", "quadratkilometer"]},
        {"canonical": "Hektar", "base": "SquareMeter_de", "factor": 10000.0, "patterns": ["ha", "hektar", "hektaren"]},
        {"canonical": "Liter", "base": "Liter", "factor": 1.0, "patterns": ["l", "liter"]},
        {"canonical": "Milliliter", "base": "Liter", "factor": 0.001, "patterns": ["ml", "milliliter"]},
        {"canonical": "Kubikmeter", "base": "Liter", "factor": 1000.0, "patterns": ["m3", "m³", "kubikmeter"]},
        {"canonical": "KilometerProStunde", "base": "KilometerProStunde", "factor": 1.0, "patterns": ["km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
        {"canonical": "Terabyte", "base": "Byte", "factor": 1000000000000.0, "patterns": ["tb"]},
    ],
    "duration": [
        {"canonical": "Sekunde", "base": "Second", "factor": 1.0, "patterns": ["sekunde", "sekunden", "sek"]},
        {"canonical": "Minute", "base": "Second", "factor": 60.0, "patterns": ["minute", "minuten", "min"]},
        {"canonical": "Stunde", "base": "Second", "factor": 3600.0, "patterns": ["stunde", "stunden", "std"]},
        {"canonical": "Tag", "base": "Second", "factor": 86400.0, "patterns": ["tag", "tage", "tagen"]},
        {"canonical": "Woche", "base": "Second", "factor": 604800.0, "patterns": ["woche", "wochen"]},
        {"canonical": "Monat", "base": "Second", "factor": 2629746.0, "patterns": ["monat", "monate", "monaten"]},
        {"canonical": "Jahr", "base": "Second", "factor": 31556952.0, "patterns": ["jahr", "jahre", "jahren"]},
    ],
    "currency": [
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro"]},
        {"canonical": "Dollar", "iso": "USD", "symbols": ["$"], "names": ["dollar", "us-dollar"]},
        {"canonical": "PfundSterling", "iso": "GBP", "symbols": ["£"], "names": ["pfund sterling", "britisches pfund"]},
        {"canonical": "Rupie", "iso": "INR", "symbols": ["₹"], "names": ["rupie", "rupien", "indische rupie"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["yen"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "grad celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "grad fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["jahre? alt"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["januar"], ["februar"], ["märz"], ["april"], ["mai"], ["juni"],
            ["juli"], ["august"], ["september"], ["oktober"], ["november"], ["dezember"],
        ],
        "weekdays": [
            ["montag"], ["dienstag"], ["mittwoch"], ["donnerstag"],
            ["freitag"], ["samstag", "sonnabend"], ["sonntag"],
        ],
        "daySuffixes": [],
        "relativeDays": {"heute": 0, "morgen": 1, "gestern": -1},
        "now": ["jetzt"],
        "timeSeparators": [":"],
        "ampm": {"am": [], "pm": []},
        "hourSuffixes": ["uhr"],
        "dateTimeConnectors": ["um", "am"],
        "numericDateSeparators": [".", "-", "/"],
    },
}

# ---------------------------------------------------------------- French
fr = {
    "culture": "fr",
    "number": {
        "decimalMark": ",", "groupMark": "\u00a0", "spaceGroup": True, "grouping": "western",
        "ordinalSuffixes": ["er", "re", "ème", "eme", "e"],
        "ordinalWords": {
            "premier": 1, "première": 1, "deuxième": 2, "second": 2, "seconde": 2,
            "troisième": 3, "quatrième": 4, "cinquième": 5, "sixième": 6,
            "septième": 7, "huitième": 8, "neuvième": 9, "dixième": 10,
            "onzième": 11, "douzième": 12, "vingtième": 20,
        },
        "atoms": {
            "zéro": 0, "un": 1, "une": 1, "deux": 2, "trois": 3, "quatre": 4,
            "cinq": 5, "six": 6, "sept": 7, "huit": 8, "neuf": 9, "dix": 10,
            "onze": 11, "douze": 12, "treize": 13, "quatorze": 14, "quinze": 15,
            "seize": 16, "dix-sept": 17, "dix-huit": 18, "dix-neuf": 19,
            "vingt": 20, "trente": 30, "quarante": 40, "cinquante": 50,
            "soixante": 60, "soixante-dix": 70, "soixante-et-onze": 71,
            "quatre-vingt": 80, "quatre-vingts": 80, "quatre-vingt-dix": 90,
        },
        "scales": {"cent": 100, "cents": 100, "mille": 1000, "million": 1000000,
                    "millions": 1000000, "milliard": 1000000000, "milliards": 1000000000},
        "connectors": ["et"],
        "negativeWords": ["moins"],
    },
    "percentage": {"suffixes": ["%", "pour cent", "pourcent"], "prefixes": []},
    "dimension": [
        {"canonical": "Metre", "base": "Metre", "factor": 1.0, "patterns": ["m", "mètre", "mètres"]},
        {"canonical": "Kilometre", "base": "Metre", "factor": 1000.0, "patterns": ["km", "kilomètre", "kilomètres"]},
        {"canonical": "Centimetre", "base": "Metre", "factor": 0.01, "patterns": ["cm", "centimètre", "centimètres"]},
        {"canonical": "Millimetre", "base": "Metre", "factor": 0.001, "patterns": ["mm", "millimètre", "millimètres"]},
        {"canonical": "Mille", "base": "Metre", "factor": 1609.344, "patterns": ["mile", "miles"]},
        {"canonical": "Kilogramme", "base": "Kilogramme", "factor": 1.0, "patterns": ["kg", "kilogramme", "kilogrammes"]},
        {"canonical": "Gramme", "base": "Kilogramme", "factor": 0.001, "patterns": ["g", "gramme", "grammes"]},
        {"canonical": "Livre", "base": "Kilogramme", "factor": 0.45359237, "patterns": ["livre", "livres"]},
        {"canonical": "MetreCarre", "base": "MetreCarre", "factor": 1.0, "patterns": ["m2", "m²", "mètre carré", "mètres carrés"]},
        {"canonical": "KilometreCarre", "base": "MetreCarre", "factor": 1000000.0, "patterns": ["km2", "km²", "kilomètre carré", "kilomètres carrés"]},
        {"canonical": "Hectare", "base": "MetreCarre", "factor": 10000.0, "patterns": ["ha", "hectare", "hectares"]},
        {"canonical": "Litre", "base": "Litre", "factor": 1.0, "patterns": ["l", "litre", "litres"]},
        {"canonical": "Millilitre", "base": "Litre", "factor": 0.001, "patterns": ["ml", "millilitre", "millilitres"]},
        {"canonical": "MetreCube", "base": "Litre", "factor": 1000.0, "patterns": ["m3", "m³", "mètre cube", "mètres cubes"]},
        {"canonical": "KilometreHeure", "base": "KilometreHeure", "factor": 1.0, "patterns": ["km/h", "kmh"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mo", "mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["go", "gb"]},
    ],
    "duration": [
        {"canonical": "Seconde", "base": "Second", "factor": 1.0, "patterns": ["seconde", "secondes"]},
        {"canonical": "Minute", "base": "Second", "factor": 60.0, "patterns": ["minute", "minutes", "min"]},
        {"canonical": "Heure", "base": "Second", "factor": 3600.0, "patterns": ["heure", "heures", "h"]},
        {"canonical": "Jour", "base": "Second", "factor": 86400.0, "patterns": ["jour", "jours"]},
        {"canonical": "Semaine", "base": "Second", "factor": 604800.0, "patterns": ["semaine", "semaines"]},
        {"canonical": "Mois", "base": "Second", "factor": 2629746.0, "patterns": ["mois"]},
        {"canonical": "An", "base": "Second", "factor": 31556952.0, "patterns": ["an", "ans", "année", "années"]},
    ],
    "currency": [
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro", "euros"]},
        {"canonical": "Dollar", "iso": "USD", "symbols": ["$"], "names": ["dollar", "dollars"]},
        {"canonical": "LivreSterling", "iso": "GBP", "symbols": ["£"], "names": ["livre sterling"]},
        {"canonical": "Roupie", "iso": "INR", "symbols": ["₹"], "names": ["roupie", "roupies", "roupies indiennes"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["yen"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "degré celsius", "degrés celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "degré fahrenheit", "degrés fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["ans"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["janvier"], ["février"], ["mars"], ["avril"], ["mai"], ["juin"],
            ["juillet"], ["août"], ["septembre"], ["octobre"], ["novembre"], ["décembre"],
        ],
        "weekdays": [
            ["lundi"], ["mardi"], ["mercredi"], ["jeudi"],
            ["vendredi"], ["samedi"], ["dimanche"],
        ],
        "daySuffixes": ["er"],
        "relativeDays": {"aujourd'hui": 0, "demain": 1, "hier": -1},
        "now": ["maintenant"],
        "timeSeparators": [":", "h"],
        "ampm": {
            "am": ["am", "du matin"],
            "pm": ["pm", "de l'après-midi", "du soir", "de la soirée"],
        },
        "hourSuffixes": [],
        "dateTimeConnectors": ["à"],
        "numericDateSeparators": ["/", "-", "."],
    },
}

# ---------------------------------------------------------------- Spanish
es = {
    "culture": "es",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["º", "er", ".º"],
        "ordinalWords": {
            "primero": 1, "primer": 1, "primera": 1, "segundo": 2, "segunda": 2,
            "tercero": 3, "tercer": 3, "tercera": 3, "cuarto": 4, "cuarta": 4,
            "quinto": 5, "quinta": 5, "sexto": 6, "sexta": 6, "séptimo": 7,
            "octavo": 8, "noveno": 9, "décimo": 10,
        },
        "atoms": {
            "cero": 0, "un": 1, "uno": 1, "una": 1, "dos": 2, "tres": 3,
            "cuatro": 4, "cinco": 5, "seis": 6, "siete": 7, "ocho": 8,
            "nueve": 9, "diez": 10, "once": 11, "doce": 12, "trece": 13,
            "catorce": 14, "quince": 15, "dieciséis": 16, "diecisiete": 17,
            "dieciocho": 18, "diecinueve": 19, "veinte": 20, "veintiuno": 21,
            "veintiún": 21, "veintidós": 22, "veintitrés": 23, "veinticuatro": 24,
            "veinticinco": 25, "veintiséis": 26, "veintisiete": 27,
            "veintiocho": 28, "veintinueve": 29, "treinta": 30, "cuarenta": 40,
            "cincuenta": 50, "sesenta": 60, "setenta": 70, "ochenta": 80, "noventa": 90,
        },
        "scales": {"cien": 100, "ciento": 100, "mil": 1000, "millón": 1000000, "millones": 1000000},
        "connectors": ["y"],
        "negativeWords": ["menos"],
    },
    "percentage": {"suffixes": ["%", "por ciento", "porciento"], "prefixes": []},
    "dimension": [
        {"canonical": "Metro", "base": "Metro", "factor": 1.0, "patterns": ["m", "metro", "metros"]},
        {"canonical": "Kilometro", "base": "Metro", "factor": 1000.0, "patterns": ["km", "kilómetro", "kilómetros"]},
        {"canonical": "Centimetro", "base": "Metro", "factor": 0.01, "patterns": ["cm", "centímetro", "centímetros"]},
        {"canonical": "Milimetro", "base": "Metro", "factor": 0.001, "patterns": ["mm", "milímetro", "milímetros"]},
        {"canonical": "Milla", "base": "Metro", "factor": 1609.344, "patterns": ["milla", "millas"]},
        {"canonical": "Kilogramo", "base": "Kilogramo", "factor": 1.0, "patterns": ["kg", "kilogramo", "kilogramos"]},
        {"canonical": "Gramo", "base": "Kilogramo", "factor": 0.001, "patterns": ["g", "gramo", "gramos"]},
        {"canonical": "Libra", "base": "Kilogramo", "factor": 0.45359237, "patterns": ["libra", "libras"]},
        {"canonical": "MetroCuadrado", "base": "MetroCuadrado", "factor": 1.0, "patterns": ["m2", "m²", "metro cuadrado", "metros cuadrados"]},
        {"canonical": "KilometroCuadrado", "base": "MetroCuadrado", "factor": 1000000.0, "patterns": ["km2", "km²", "kilómetro cuadrado", "kilómetros cuadrados"]},
        {"canonical": "Hectarea", "base": "MetroCuadrado", "factor": 10000.0, "patterns": ["ha", "hectárea", "hectáreas"]},
        {"canonical": "Litro", "base": "Litro", "factor": 1.0, "patterns": ["l", "litro", "litros"]},
        {"canonical": "Mililitro", "base": "Litro", "factor": 0.001, "patterns": ["ml", "mililitro", "mililitros"]},
        {"canonical": "MetroCubico", "base": "Litro", "factor": 1000.0, "patterns": ["m3", "m³", "metro cúbico", "metros cúbicos"]},
        {"canonical": "KilometroHora", "base": "KilometroHora", "factor": 1.0, "patterns": ["km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Segundo", "base": "Second", "factor": 1.0, "patterns": ["segundo", "segundos"]},
        {"canonical": "Minuto", "base": "Second", "factor": 60.0, "patterns": ["minuto", "minutos", "min"]},
        {"canonical": "Hora", "base": "Second", "factor": 3600.0, "patterns": ["hora", "horas"]},
        {"canonical": "Dia", "base": "Second", "factor": 86400.0, "patterns": ["día", "días"]},
        {"canonical": "Semana", "base": "Second", "factor": 604800.0, "patterns": ["semana", "semanas"]},
        {"canonical": "Mes", "base": "Second", "factor": 2629746.0, "patterns": ["mes", "meses"]},
        {"canonical": "Ano", "base": "Second", "factor": 31556952.0, "patterns": ["año", "años"]},
    ],
    "currency": [
        {"canonical": "Dolar", "iso": "USD", "symbols": ["$"], "names": ["dólar", "dólares", "dolares"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro", "euros"]},
        {"canonical": "LibraSterlina", "iso": "GBP", "symbols": ["£"], "names": ["libra esterlina"]},
        {"canonical": "Rupia", "iso": "INR", "symbols": ["₹"], "names": ["rupia", "rupias"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["yen"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "grado celsius", "grados celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "grado fahrenheit", "grados fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["años de edad", "anos de edad"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["enero", "ene"], ["febrero", "feb"], ["marzo"], ["abril", "abr"],
            ["mayo"], ["junio"], ["julio"], ["agosto", "ago"],
            ["septiembre", "setiembre", "sep"], ["octubre", "oct"],
            ["noviembre", "nov"], ["diciembre", "dic"],
        ],
        "weekdays": [
            ["lunes"], ["martes"], ["miércoles"], ["jueves"],
            ["viernes"], ["sábado"], ["domingo"],
        ],
        "daySuffixes": [],
        "dayMonthConnector": "de",
        "yearConnector": "de",
        "relativeDays": {"hoy": 0, "mañana": 1, "ayer": -1},
        "now": ["ahora"],
        "timeSeparators": [":"],
        "ampm": {
            "am": ["am", "de la mañana", "de la madrugada"],
            "pm": ["pm", "de la tarde", "de la noche", "de la noche"],
        },
        "hourSuffixes": [],
        "dateTimeConnectors": ["a las", "a la", "a"],
        "numericDateSeparators": ["/", "-", "."],
    },
}

# ---------------------------------------------------------------- Portuguese
pt = {
    "culture": "pt",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["º", "ª", ".º"],
        "ordinalWords": {
            "primeiro": 1, "primeira": 1, "segundo": 2, "segunda": 2,
            "terceiro": 3, "terceira": 3, "quarto": 4, "quarta": 4,
            "quinto": 5, "quinta": 5, "sexto": 6, "sexta": 6,
            "sétimo": 7, "oitavo": 8, "nono": 9, "décimo": 10,
        },
        "atoms": {
            "zero": 0, "um": 1, "uma": 1, "dois": 2, "duas": 2, "três": 3,
            "quatro": 4, "cinco": 5, "seis": 6, "sete": 7, "oito": 8,
            "nove": 9, "dez": 10, "onze": 11, "doze": 12, "treze": 13,
            "catorze": 14, "quatorze": 14, "quinze": 15, "dezesseis": 16,
            "dezasseis": 16, "dezessete": 17, "dezassete": 17, "dezoito": 18,
            "dezenove": 19, "dezanove": 19, "vinte": 20, "trinta": 30,
            "quarenta": 40, "cinquenta": 50, "sessenta": 60, "setenta": 70,
            "oitenta": 80, "noventa": 90,
        },
        "scales": {"cem": 100, "cento": 100, "mil": 1000, "milhão": 1000000, "milhões": 1000000},
        "connectors": ["e"],
        "negativeWords": ["menos"],
    },
    "percentage": {"suffixes": ["%", "por cento"], "prefixes": []},
    "dimension": [
        {"canonical": "Metro", "base": "Metro", "factor": 1.0, "patterns": ["m", "metro", "metros"]},
        {"canonical": "Quilometro", "base": "Metro", "factor": 1000.0, "patterns": ["km", "quilômetro", "quilômetros", "quilómetro", "quilómetros"]},
        {"canonical": "Centimetro", "base": "Metro", "factor": 0.01, "patterns": ["cm", "centímetro", "centímetros"]},
        {"canonical": "Milimetro", "base": "Metro", "factor": 0.001, "patterns": ["mm", "milímetro", "milímetros"]},
        {"canonical": "Milha", "base": "Metro", "factor": 1609.344, "patterns": ["milha", "milhas"]},
        {"canonical": "Quilograma", "base": "Quilograma", "factor": 1.0, "patterns": ["kg", "quilograma", "quilogramas"]},
        {"canonical": "Grama", "base": "Quilograma", "factor": 0.001, "patterns": ["g", "grama", "gramas"]},
        {"canonical": "Libra", "base": "Quilograma", "factor": 0.45359237, "patterns": ["libra", "libras"]},
        {"canonical": "MetroQuadrado", "base": "MetroQuadrado", "factor": 1.0, "patterns": ["m2", "m²", "metro quadrado", "metros quadrados"]},
        {"canonical": "QuilometroQuadrado", "base": "MetroQuadrado", "factor": 1000000.0, "patterns": ["km2", "km²", "quilômetro quadrado", "quilômetros quadrados"]},
        {"canonical": "Hectare", "base": "MetroQuadrado", "factor": 10000.0, "patterns": ["ha", "hectare", "hectares"]},
        {"canonical": "Litro", "base": "Litro", "factor": 1.0, "patterns": ["l", "litro", "litros"]},
        {"canonical": "Mililitro", "base": "Litro", "factor": 0.001, "patterns": ["ml", "mililitro", "mililitros"]},
        {"canonical": "MetroCubico", "base": "Litro", "factor": 1000.0, "patterns": ["m3", "m³", "metro cúbico", "metros cúbicos"]},
        {"canonical": "QuilometroHora", "base": "QuilometroHora", "factor": 1.0, "patterns": ["km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Segundo", "base": "Second", "factor": 1.0, "patterns": ["segundo", "segundos"]},
        {"canonical": "Minuto", "base": "Second", "factor": 60.0, "patterns": ["minuto", "minutos", "min"]},
        {"canonical": "Hora", "base": "Second", "factor": 3600.0, "patterns": ["hora", "horas"]},
        {"canonical": "Dia", "base": "Second", "factor": 86400.0, "patterns": ["dia", "dias"]},
        {"canonical": "Semana", "base": "Second", "factor": 604800.0, "patterns": ["semana", "semanas"]},
        {"canonical": "Mes", "base": "Second", "factor": 2629746.0, "patterns": ["mês", "meses"]},
        {"canonical": "Ano", "base": "Second", "factor": 31556952.0, "patterns": ["ano", "anos"]},
    ],
    "currency": [
        {"canonical": "Dolar", "iso": "USD", "symbols": ["$"], "names": ["dólar", "dólares", "dolares"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro", "euros"]},
        {"canonical": "Libra", "iso": "GBP", "symbols": ["£"], "names": ["libra esterlina"]},
        {"canonical": "Rupia", "iso": "INR", "symbols": ["₹"], "names": ["rupia", "rúpias", "rupias"]},
        {"canonical": "Iene", "iso": "JPY", "symbols": ["¥"], "names": ["iene", "ien"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "grau celsius", "graus celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "grau fahrenheit", "graus fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["anos de idade"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["janeiro", "jan"], ["fevereiro", "fev"], ["março"], ["abril", "abr"],
            ["maio"], ["junho", "jun"], ["julho", "jul"], ["agosto", "ago"],
            ["setembro", "set"], ["outubro", "out"], ["novembro", "nov"], ["dezembro", "dez"],
        ],
        "weekdays": [
            ["segunda-feira", "segunda"], ["terça-feira", "terça"], ["quarta-feira", "quarta"],
            ["quinta-feira", "quinta"], ["sexta-feira", "sexta"],
            ["sábado"], ["domingo"],
        ],
        "daySuffixes": [],
        "dayMonthConnector": "de",
        "yearConnector": "de",
        "relativeDays": {"hoje": 0, "amanhã": 1, "ontem": -1},
        "now": ["agora"],
        "timeSeparators": [":"],
        "ampm": {
            "am": ["am", "da manhã", "da madrugada"],
            "pm": ["pm", "da tarde", "da noite", "da noite"],
        },
        "hourSuffixes": [],
        "dateTimeConnectors": ["às", "à", "as"],
        "numericDateSeparators": ["/", "-", "."],
    },
}

# ---------------------------------------------------------------- Italian
it = {
    "culture": "it",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["º", "°", "o"],
        "ordinalWords": {
            "primo": 1, "prima": 1, "secondo": 2, "seconda": 2, "terzo": 3,
            "terza": 3, "quarto": 4, "quarta": 4, "quinto": 5, "quinta": 5,
            "sesto": 6, "sesta": 6, "settimo": 7, "ottavo": 8, "nono": 9, "decimo": 10,
        },
        "atoms": {
            "zero": 0, "uno": 1, "una": 1, "due": 2, "tre": 3, "quattro": 4,
            "cinque": 5, "sei": 6, "sette": 7, "otto": 8, "nove": 9, "dieci": 10,
            "undici": 11, "dodici": 12, "tredici": 13, "quattordici": 14,
            "quindici": 15, "sedici": 16, "diciassette": 17, "diciotto": 18,
            "diciannove": 19, "venti": 20, "ventuno": 21, "ventidue": 22,
            "ventitré": 23, "ventiquattro": 24, "venticinque": 25, "ventisei": 26,
            "ventisette": 27, "ventotto": 28, "ventinove": 29, "trenta": 30,
            "quaranta": 40, "cinquanta": 50, "sessanta": 60, "settanta": 70,
            "ottanta": 80, "novanta": 90,
        },
        "scales": {"cento": 100, "mille": 1000, "mila": 1000, "milione": 1000000, "milioni": 1000000},
        "connectors": [],
        "negativeWords": ["meno"],
    },
    "percentage": {"suffixes": ["%", "per cento", "percento"], "prefixes": []},
    "dimension": [
        {"canonical": "Metro", "base": "Metro", "factor": 1.0, "patterns": ["m", "metro", "metri"]},
        {"canonical": "Chilometro", "base": "Metro", "factor": 1000.0, "patterns": ["km", "chilometro", "chilometri"]},
        {"canonical": "Centimetro", "base": "Metro", "factor": 0.01, "patterns": ["cm", "centimetro", "centimetri"]},
        {"canonical": "Millimetro", "base": "Metro", "factor": 0.001, "patterns": ["mm", "millimetro", "millimetri"]},
        {"canonical": "Miglio", "base": "Metro", "factor": 1609.344, "patterns": ["miglio", "miglia"]},
        {"canonical": "Chilogrammo", "base": "Chilogrammo", "factor": 1.0, "patterns": ["kg", "chilogrammo", "chilogrammi"]},
        {"canonical": "Grammo", "base": "Chilogrammo", "factor": 0.001, "patterns": ["g", "grammo", "grammi"]},
        {"canonical": "Libbra", "base": "Chilogrammo", "factor": 0.45359237, "patterns": ["libbra", "libbre"]},
        {"canonical": "MetroQuadro", "base": "MetroQuadro", "factor": 1.0, "patterns": ["m2", "m²", "metro quadro", "metri quadri", "metro quadrato", "metri quadrati"]},
        {"canonical": "ChilometroQuadro", "base": "MetroQuadro", "factor": 1000000.0, "patterns": ["km2", "km²", "chilometro quadro", "chilometri quadri"]},
        {"canonical": "Ettaro", "base": "MetroQuadro", "factor": 10000.0, "patterns": ["ha", "ettaro", "ettari"]},
        {"canonical": "Litro", "base": "Litro", "factor": 1.0, "patterns": ["l", "litro", "litri"]},
        {"canonical": "Millilitro", "base": "Litro", "factor": 0.001, "patterns": ["ml", "millilitro", "millilitri"]},
        {"canonical": "MetroCubo", "base": "Litro", "factor": 1000.0, "patterns": ["m3", "m³", "metro cubo", "metri cubi"]},
        {"canonical": "ChilometroOra", "base": "ChilometroOra", "factor": 1.0, "patterns": ["km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Secondo", "base": "Second", "factor": 1.0, "patterns": ["secondo", "secondi"]},
        {"canonical": "Minuto", "base": "Second", "factor": 60.0, "patterns": ["minuto", "minuti", "min"]},
        {"canonical": "Ora", "base": "Second", "factor": 3600.0, "patterns": ["ora", "ore"]},
        {"canonical": "Giorno", "base": "Second", "factor": 86400.0, "patterns": ["giorno", "giorni"]},
        {"canonical": "Settimana", "base": "Second", "factor": 604800.0, "patterns": ["settimana", "settimane"]},
        {"canonical": "Mese", "base": "Second", "factor": 2629746.0, "patterns": ["mese", "mesi"]},
        {"canonical": "Anno", "base": "Second", "factor": 31556952.0, "patterns": ["anno", "anni"]},
    ],
    "currency": [
        {"canonical": "Dollaro", "iso": "USD", "symbols": ["$"], "names": ["dollaro", "dollari"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro"]},
        {"canonical": "Sterlina", "iso": "GBP", "symbols": ["£"], "names": ["sterlina", "sterline"]},
        {"canonical": "Rupia", "iso": "INR", "symbols": ["₹"], "names": ["rupia", "rupie"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["yen"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "grado celsius", "gradi celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "grado fahrenheit", "gradi fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["anni di età", "anni d'età"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["gennaio", "gen"], ["febbraio", "feb"], ["marzo"], ["aprile"],
            ["maggio"], ["giugno"], ["luglio"], ["agosto", "ago"],
            ["settembre", "set"], ["ottobre", "ott"], ["novembre", "nov"], ["dicembre", "dic"],
        ],
        "weekdays": [
            ["lunedì"], ["martedì"], ["mercoledì"], ["giovedì"],
            ["venerdì"], ["sabato"], ["domenica"],
        ],
        "daySuffixes": [],
        "relativeDays": {"oggi": 0, "domani": 1, "ieri": -1},
        "now": ["adesso", "ora"],
        "timeSeparators": [":"],
        "ampm": {
            "am": ["am", "del mattino", "di mattina"],
            "pm": ["pm", "del pomeriggio", "della sera", "di sera", "di notte"],
        },
        "hourSuffixes": [],
        "dateTimeConnectors": ["alle", "all'", "a"],
        "numericDateSeparators": ["/", "-", "."],
    },
}

# ---------------------------------------------------------------- Turkish
tr = {
    "culture": "tr",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["."],
        "ordinalWords": {
            "birinci": 1, "ilk": 1, "ikinci": 2, "üçüncü": 3, "dördüncü": 4,
            "beşinci": 5, "altıncı": 6, "yedinci": 7, "sekizinci": 8,
            "dokuzuncu": 9, "onuncu": 10,
        },
        "atoms": {
            "sıfır": 0, "bir": 1, "iki": 2, "üç": 3, "dört": 4, "beş": 5,
            "altı": 6, "yedi": 7, "sekiz": 8, "dokuz": 9, "on": 10,
            "yirmi": 20, "otuz": 30, "kırk": 40, "elli": 50, "altmış": 60,
            "yetmiş": 70, "seksen": 80, "doksan": 90,
        },
        "scales": {"yüz": 100, "bin": 1000, "milyon": 1000000, "milyar": 1000000000},
        "connectors": [],
        "negativeWords": ["eksi"],
    },
    "percentage": {"suffixes": ["%"], "prefixes": ["%", "yüzde"]},
    "dimension": [
        {"canonical": "Metre", "base": "Metre", "factor": 1.0, "patterns": ["m", "metre"]},
        {"canonical": "Kilometre", "base": "Metre", "factor": 1000.0, "patterns": ["km", "kilometre"]},
        {"canonical": "Santimetre", "base": "Metre", "factor": 0.01, "patterns": ["cm", "santimetre"]},
        {"canonical": "Milimetre", "base": "Metre", "factor": 0.001, "patterns": ["mm", "milimetre"]},
        {"canonical": "Mil", "base": "Metre", "factor": 1609.344, "patterns": ["mil"]},
        {"canonical": "Kilogram", "base": "Kilogram", "factor": 1.0, "patterns": ["kg", "kilogram"]},
        {"canonical": "Gram", "base": "Kilogram", "factor": 0.001, "patterns": ["g", "gram"]},
        {"canonical": "Milligram", "base": "Kilogram", "factor": 1e-06, "patterns": ["mg", "miligram"]},
        {"canonical": "Metrekare", "base": "Metrekare", "factor": 1.0, "patterns": ["m2", "m²", "metrekare"]},
        {"canonical": "Kilometrekare", "base": "Metrekare", "factor": 1000000.0, "patterns": ["km2", "km²", "kilometrekare"]},
        {"canonical": "Hektar", "base": "Metrekare", "factor": 10000.0, "patterns": ["ha", "hektar"]},
        {"canonical": "Dönüm", "base": "Metrekare", "factor": 1000.0, "patterns": ["dönüm", "donum"]},
        {"canonical": "Litre", "base": "Litre", "factor": 1.0, "patterns": ["l", "litre"]},
        {"canonical": "Mililitre", "base": "Litre", "factor": 0.001, "patterns": ["ml", "mililitre"]},
        {"canonical": "Metreküp", "base": "Litre", "factor": 1000.0, "patterns": ["m3", "m³", "metreküp"]},
        {"canonical": "KilometreSaat", "base": "KilometreSaat", "factor": 1.0, "patterns": ["km/h", "km-sa"]},
        {"canonical": "Megabayt", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabayt", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Saniye", "base": "Second", "factor": 1.0, "patterns": ["saniye", "sn"]},
        {"canonical": "Dakika", "base": "Second", "factor": 60.0, "patterns": ["dakika", "dk"]},
        {"canonical": "Saat", "base": "Second", "factor": 3600.0, "patterns": ["saat"]},
        {"canonical": "Gün", "base": "Second", "factor": 86400.0, "patterns": ["gün"]},
        {"canonical": "Hafta", "base": "Second", "factor": 604800.0, "patterns": ["hafta"]},
        {"canonical": "Ay", "base": "Second", "factor": 2629746.0, "patterns": ["ay"]},
        {"canonical": "Yıl", "base": "Second", "factor": 31556952.0, "patterns": ["yıl"]},
    ],
    "currency": [
        {"canonical": "TurkLirasi", "iso": "TRY", "symbols": ["₺"], "names": ["türk lirası", "lira", "tl"]},
        {"canonical": "Dolar", "iso": "USD", "symbols": ["$"], "names": ["dolar"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro"]},
        {"canonical": "Sterlin", "iso": "GBP", "symbols": ["£"], "names": ["sterlin"]},
        {"canonical": "Rupi", "iso": "INR", "symbols": ["₹"], "names": ["rupi"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "santigrat", "celsius", "derece celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["yaşında", "yaş"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["ocak"], ["şubat"], ["mart"], ["nisan"], ["mayıs"], ["haziran"],
            ["temmuz"], ["ağustos"], ["eylül"], ["ekim"], ["kasım"], ["aralık"],
        ],
        "weekdays": [
            ["pazartesi"], ["salı"], ["çarşamba"], ["perşembe"],
            ["cuma"], ["cumartesi"], ["pazar"],
        ],
        "daySuffixes": [],
        "relativeDays": {"bugün": 0, "yarın": 1, "dün": -1},
        "now": ["şimdi", "şu an"],
        "timeSeparators": [":"],
        "ampm": {
            "am": ["öö", "ö.ö.", "sabah"],
            "pm": ["ös", "ö.s.", "öğleden sonra", "akşam", "gece"],
        },
        "hourSuffixes": [],
        "dateTimeConnectors": ["saat"],
        "numericDateSeparators": ["/", ".", "-"],
    },
}

# ---------------------------------------------------------------- Hindi
hi = {
    "culture": "hi",
    "number": {
        "decimalMark": ".", "groupMark": ",", "spaceGroup": False, "grouping": "indian",
        "ordinalSuffixes": ["वाँ", "वां", "वें", "वीं"],
        "ordinalWords": {
            "पहला": 1, "पहली": 1, "दूसरा": 2, "दूसरी": 2, "तीसरा": 3, "तीसरी": 3,
            "चौथा": 4, "चौथी": 4, "पाँचवाँ": 5, "पांचवां": 5, "छठा": 6, "सातवाँ": 7,
            "आठवाँ": 8, "नौवाँ": 9, "दसवाँ": 10,
        },
        "atoms": {
            "शून्य": 0, "एक": 1, "दो": 2, "तीन": 3, "चार": 4, "पाँच": 5, "पांच": 5,
            "छह": 6, "छः": 6, "सात": 7, "आठ": 8, "नौ": 9, "दस": 10,
            "ग्यारह": 11, "बारह": 12, "तेरह": 13, "चौदह": 14, "पंद्रह": 15,
            "सोलह": 16, "सत्रह": 17, "अठारह": 18, "उन्नीस": 19, "बीस": 20,
            "तीस": 30, "चालीस": 40, "पचास": 50, "साठ": 60, "सत्तर": 70,
            "अस्सी": 80, "नब्बे": 90,
        },
        "scales": {"सौ": 100, "हज़ार": 1000, "हजार": 1000, "लाख": 100000, "करोड़": 10000000},
        "connectors": [],
        "negativeWords": ["ऋण"],
    },
    "percentage": {"suffixes": ["%", "प्रतिशत"], "prefixes": []},
    "dimension": [
        {"canonical": "Meter", "base": "Meter", "factor": 1.0, "patterns": ["मीटर", "m"]},
        {"canonical": "Kilometer", "base": "Meter", "factor": 1000.0, "patterns": ["किलोमीटर", "km"]},
        {"canonical": "Centimeter", "base": "Meter", "factor": 0.01, "patterns": ["सेंटीमीटर", "cm"]},
        {"canonical": "Millimeter", "base": "Meter", "factor": 0.001, "patterns": ["मिलीमीटर", "mm"]},
        {"canonical": "Kilogram", "base": "Kilogram", "factor": 1.0, "patterns": ["किलोग्राम", "किलो", "kg"]},
        {"canonical": "Gram", "base": "Kilogram", "factor": 0.001, "patterns": ["ग्राम", "g"]},
        {"canonical": "SquareMeter", "base": "SquareMeter", "factor": 1.0, "patterns": ["वर्ग मीटर", "m2", "m²"]},
        {"canonical": "SquareKilometer", "base": "SquareMeter", "factor": 1000000.0, "patterns": ["वर्ग किलोमीटर", "km2", "km²"]},
        {"canonical": "Hectare", "base": "SquareMeter", "factor": 10000.0, "patterns": ["हेक्टेयर", "ha"]},
        {"canonical": "Acre", "base": "SquareMeter", "factor": 4046.8564224, "patterns": ["एकड़", "एकड़े", "acre"]},
        {"canonical": "Liter", "base": "Liter", "factor": 1.0, "patterns": ["लीटर", "l"]},
        {"canonical": "Milliliter", "base": "Liter", "factor": 0.001, "patterns": ["मिलीलीटर", "ml"]},
        {"canonical": "KilometerPerHour", "base": "KilometerPerHour", "factor": 1.0, "patterns": ["किमी/घंटा", "km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Second", "base": "Second", "factor": 1.0, "patterns": ["सेकंड", "सेकेंड"]},
        {"canonical": "Minute", "base": "Second", "factor": 60.0, "patterns": ["मिनट"]},
        {"canonical": "Hour", "base": "Second", "factor": 3600.0, "patterns": ["घंटा", "घंटे"]},
        {"canonical": "Day", "base": "Second", "factor": 86400.0, "patterns": ["दिन"]},
        {"canonical": "Week", "base": "Second", "factor": 604800.0, "patterns": ["सप्ताह", "हफ्ते", "हफ्ता"]},
        {"canonical": "Month", "base": "Second", "factor": 2629746.0, "patterns": ["महीना", "महीने"]},
        {"canonical": "Year", "base": "Second", "factor": 31556952.0, "patterns": ["साल", "वर्ष"]},
    ],
    "currency": [
        {"canonical": "Rupee", "iso": "INR", "symbols": ["₹"], "names": ["रुपया", "रुपये", "रु"]},
        {"canonical": "Dollar", "iso": "USD", "symbols": ["$"], "names": ["डॉलर"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["यूरो"]},
        {"canonical": "PoundSterling", "iso": "GBP", "symbols": ["£"], "names": ["पाउंड"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["येन"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "डिग्री सेल्सियस", "सेल्सियस"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "फ़ारेनहाइट"]},
    ],
    "age": {"unit": "Year", "patterns": ["साल का", "साल की", "साल के"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["जनवरी"], ["फ़रवरी", "फरवरी"], ["मार्च"], ["अप्रैल"], ["मई"], ["जून"],
            ["जुलाई"], ["अगस्त"], ["सितंबर", "सितम्बर"], ["अक्टूबर"],
            ["नवंबर", "नवम्बर"], ["दिसंबर", "दिसम्बर"],
        ],
        "weekdays": [
            ["सोमवार"], ["मंगलवार"], ["बुधवार"], ["गुरुवार", "बृहस्पतिवार"],
            ["शुक्रवार"], ["शनिवार"], ["रविवार"],
        ],
        "daySuffixes": [],
        "relativeDays": {"आज": 0},
        "now": ["अभी", "अब"],
        "timeSeparators": [":", "."],
        "ampm": {"am": [], "pm": []},
        "hourSuffixes": [],
        "hiPartOfDay": {"am": ["सुबह", "पहाल"], "pm": ["दोपहर", "शाम", "रात"]},
        "hiOClock": "बजे",
        "dateTimeConnectors": ["को", "पर"],
        "numericDateSeparators": ["/", ".", "-"],
    },
}

# ---------------------------------------------------------------- Dutch
nl = {
    "culture": "nl",
    "number": {
        "decimalMark": ",", "groupMark": ".", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": ["ste", "e"],
        "ordinalWords": {
            "eerste": 1, "tweede": 2, "derde": 3, "vierde": 4, "vijfde": 5,
            "zesde": 6, "zevende": 7, "achtste": 8, "negende": 9, "tiende": 10,
            "elfde": 11, "twaalfde": 12, "twintigste": 20,
        },
        "atoms": {
            "nul": 0, "een": 1, "één": 1, "twee": 2, "drie": 3, "vier": 4,
            "vijf": 5, "zes": 6, "zeven": 7, "acht": 8, "negen": 9, "tien": 10,
            "elf": 11, "twaalf": 12, "dertien": 13, "veertien": 14, "vijftien": 15,
            "zestien": 16, "zeventien": 17, "achttien": 18, "negentien": 19,
            "twintig": 20, "dertig": 30, "veertig": 40, "vijftig": 50,
            "zestig": 60, "zeventig": 70, "tachtig": 80, "negentig": 90,
            **compounds["nl"],
        },
        "scales": {"honderd": 100, "duizend": 1000, "miljoen": 1000000, "miljard": 1000000000},
        "connectors": [],
        "negativeWords": ["min"],
    },
    "percentage": {"suffixes": ["%", "procent"], "prefixes": []},
    "dimension": [
        {"canonical": "Meter", "base": "Meter", "factor": 1.0, "patterns": ["m", "meter"]},
        {"canonical": "Kilometer", "base": "Meter", "factor": 1000.0, "patterns": ["km", "kilometer"]},
        {"canonical": "Centimeter", "base": "Meter", "factor": 0.01, "patterns": ["cm", "centimeter"]},
        {"canonical": "Millimeter", "base": "Meter", "factor": 0.001, "patterns": ["mm", "millimeter"]},
        {"canonical": "Mijl", "base": "Meter", "factor": 1609.344, "patterns": ["mijl", "mijlen"]},
        {"canonical": "Kilogram", "base": "Kilogram", "factor": 1.0, "patterns": ["kg", "kilogram"]},
        {"canonical": "Gram", "base": "Kilogram", "factor": 0.001, "patterns": ["g", "gram"]},
        {"canonical": "Pond", "base": "Kilogram", "factor": 0.5, "patterns": ["pond"]},
        {"canonical": "VierkanteMeter", "base": "VierkanteMeter", "factor": 1.0, "patterns": ["m2", "m²", "vierkante meter", "vierkante meters"]},
        {"canonical": "VierkanteKilometer", "base": "VierkanteMeter", "factor": 1000000.0, "patterns": ["km2", "km²", "vierkante kilometer", "vierkante kilometers"]},
        {"canonical": "Hectare", "base": "VierkanteMeter", "factor": 10000.0, "patterns": ["ha", "hectare", "hectaren"]},
        {"canonical": "Liter", "base": "Liter", "factor": 1.0, "patterns": ["l", "liter"]},
        {"canonical": "Milliliter", "base": "Liter", "factor": 0.001, "patterns": ["ml", "milliliter"]},
        {"canonical": "KubiekeMeter", "base": "Liter", "factor": 1000.0, "patterns": ["m3", "m³", "kubieke meter", "kubieke meters"]},
        {"canonical": "KilometerPerUur", "base": "KilometerPerUur", "factor": 1.0, "patterns": ["km/u", "km/h", "km/uur"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Seconde", "base": "Second", "factor": 1.0, "patterns": ["seconde", "seconden", "sec"]},
        {"canonical": "Minuut", "base": "Second", "factor": 60.0, "patterns": ["minuut", "minuten", "min"]},
        {"canonical": "Uur", "base": "Second", "factor": 3600.0, "patterns": ["uur", "u"]},
        {"canonical": "Dag", "base": "Second", "factor": 86400.0, "patterns": ["dag", "dagen"]},
        {"canonical": "Week", "base": "Second", "factor": 604800.0, "patterns": ["week", "weken"]},
        {"canonical": "Maand", "base": "Second", "factor": 2629746.0, "patterns": ["maand", "maanden"]},
        {"canonical": "Jaar", "base": "Second", "factor": 31556952.0, "patterns": ["jaar", "jaren"]},
    ],
    "currency": [
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["euro"]},
        {"canonical": "Dollar", "iso": "USD", "symbols": ["$"], "names": ["dollar", "dollars"]},
        {"canonical": "PondSterling", "iso": "GBP", "symbols": ["£"], "names": ["pond sterling"]},
        {"canonical": "Roepie", "iso": "INR", "symbols": ["₹"], "names": ["roepie", "roepies"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": ["¥"], "names": ["yen"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "celsius", "graden celsius"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "fahrenheit", "graden fahrenheit"]},
    ],
    "age": {"unit": "Year", "patterns": ["jaar oud", "jaar oude"]},
    "datetime": {
        "dateOrder": "DMY",
        "monthDayFormats": ["day-first"],
        "months": [
            ["januari", "jan"], ["februari", "feb"], ["maart"], ["april"],
            ["mei"], ["juni", "jun"], ["juli", "jul"], ["augustus", "aug"],
            ["september", "sep"], ["oktober", "okt"], ["november", "nov"], ["december", "dec"],
        ],
        "weekdays": [
            ["maandag"], ["dinsdag"], ["woensdag"], ["donderdag"],
            ["vrijdag"], ["zaterdag"], ["zondag"],
        ],
        "daySuffixes": [],
        "relativeDays": {"vandaag": 0, "morgen": 1, "gisteren": -1},
        "now": ["nu"],
        "timeSeparators": [":", "."],
        "ampm": {
            "am": ["'s ochtends", "'s morgens", "'s nachts"],
            "pm": ["'s middags", "'s avonds"],
        },
        "hourSuffixes": ["uur"],
        "dateTimeConnectors": ["om"],
        "numericDateSeparators": ["-", "/", "."],
    },
}

# ---------------------------------------------------------------- Chinese
zh = {
    "culture": "zh",
    "number": {
        "decimalMark": ".", "groupMark": ",", "spaceGroup": False, "grouping": "western",
        "ordinalSuffixes": [],
        "ordinalWords": {},
        "atoms": {},
        "scales": {},
        "connectors": [],
        "negativeWords": [],
    },
    "percentage": {"suffixes": ["%"], "prefixes": ["%", "百分之"]},
    "dimension": [
        {"canonical": "Meter", "base": "Meter", "factor": 1.0, "patterns": ["米", "m"]},
        {"canonical": "Kilometer", "base": "Meter", "factor": 1000.0, "patterns": ["公里", "千米", "km"]},
        {"canonical": "Centimeter", "base": "Meter", "factor": 0.01, "patterns": ["厘米", "cm"]},
        {"canonical": "Millimeter", "base": "Meter", "factor": 0.001, "patterns": ["毫米", "mm"]},
        {"canonical": "Kilogram", "base": "Kilogram", "factor": 1.0, "patterns": ["公斤", "千克", "kg"]},
        {"canonical": "Gram", "base": "Kilogram", "factor": 0.001, "patterns": ["克", "g"]},
        {"canonical": "SquareMeter", "base": "SquareMeter", "factor": 1.0, "patterns": ["平方米", "m2", "m²"]},
        {"canonical": "SquareKilometer", "base": "SquareMeter", "factor": 1000000.0, "patterns": ["平方公里", "km2", "km²"]},
        {"canonical": "Hectare", "base": "SquareMeter", "factor": 10000.0, "patterns": ["公顷", "ha"]},
        {"canonical": "Mu", "base": "SquareMeter", "factor": 666.6666666666667, "patterns": ["亩"]},
        {"canonical": "Liter", "base": "Liter", "factor": 1.0, "patterns": ["升", "l"]},
        {"canonical": "Milliliter", "base": "Liter", "factor": 0.001, "patterns": ["毫升", "ml"]},
        {"canonical": "KilometerPerHour", "base": "KilometerPerHour", "factor": 1.0, "patterns": ["km/h"]},
        {"canonical": "Megabyte", "base": "Byte", "factor": 1000000.0, "patterns": ["mb"]},
        {"canonical": "Gigabyte", "base": "Byte", "factor": 1000000000.0, "patterns": ["gb"]},
    ],
    "duration": [
        {"canonical": "Second", "base": "Second", "factor": 1.0, "patterns": ["秒"]},
        {"canonical": "Minute", "base": "Second", "factor": 60.0, "patterns": ["分钟", "分"]},
        {"canonical": "Hour", "base": "Second", "factor": 3600.0, "patterns": ["小时"]},
        {"canonical": "Day", "base": "Second", "factor": 86400.0, "patterns": ["天"]},
        {"canonical": "Week", "base": "Second", "factor": 604800.0, "patterns": ["周", "星期"]},
        {"canonical": "Year", "base": "Second", "factor": 31556952.0, "patterns": ["年"]},
    ],
    "currency": [
        {"canonical": "ChineseYuan", "iso": "CNY", "symbols": ["¥", "￥", "元"], "names": ["人民币", "元", "块"]},
        {"canonical": "Dollar", "iso": "USD", "symbols": ["$"], "names": ["美元"]},
        {"canonical": "Euro", "iso": "EUR", "symbols": ["€"], "names": ["欧元"]},
        {"canonical": "PoundSterling", "iso": "GBP", "symbols": ["£"], "names": ["英镑"]},
        {"canonical": "Rupee", "iso": "INR", "symbols": ["₹"], "names": ["卢比"]},
        {"canonical": "Yen", "iso": "JPY", "symbols": [], "names": ["日元"]},
    ],
    "temperature": [
        {"canonical": "Celsius", "base": "Kelvin", "factor": 1.0, "offset": 273.15,
         "patterns": ["° c", "°c", "摄氏度", "摄氏"]},
        {"canonical": "Fahrenheit", "base": "Kelvin", "factor": 0.5555555555555556, "offset": 255.3722222222222,
         "patterns": ["° f", "°f", "华氏度", "华氏"]},
    ],
    "age": {"unit": "Year", "patterns": ["岁"]},
    "datetime": {
        "dateOrder": "YMD",
        "monthDayFormats": [],
        "months": [],
        "weekdays": [],
        "daySuffixes": [],
        "relativeDays": {"今天": 0, "明天": 1, "昨天": -1},
        "now": ["现在"],
        "timeSeparators": [":"],
        "ampm": {"am": [], "pm": []},
        "zhAmpm": {"am": ["凌晨", "早上", "上午"], "pm": ["下午", "傍晚", "晚上"]},
        "hourMarkers": ["点", "时"],
        "dateTimeConnectors": [],
        "numericDateSeparators": [],
    },
}

for name, data in [("de", de), ("fr", fr), ("es", es), ("pt", pt), ("it", it),
                   ("tr", tr), ("hi", hi), ("nl", nl), ("zh", zh)]:
    path = OUT / f"{name}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path} ({path.stat().st_size} bytes)")
