/**
 * Client-Side Legal Document & Report Exporter for Chrome / Browser
 * Generates instant, certified-format PDF, Word (.doc), Markdown, and Plain Text downloads.
 */

export interface LegalReportData {
  id?: string;
  title: string;
  created_at?: string;
  completed_at?: string;
  content: Record<string, any>;
}

/**
 * Trigger direct file download in Chrome / Browser
 */
export function triggerBrowserDownload(content: BlobPart, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Clean file name for filesystem
 */
function sanitizeFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 80);
}

/**
 * Export Legal Report as Word Document (.doc / XML)
 */
export function downloadReportAsWord(report: LegalReportData, caseName = "Case") {
  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let sectionsHtml = "";
  for (const [section, value] of Object.entries(report.content || {})) {
    const heading = section.replace(/_/g, " ").toUpperCase();
    let bodyHtml = "";

    if (typeof value === "string") {
      bodyHtml = `<p style="font-size: 11pt; line-height: 1.6; margin-bottom: 12pt; color: #222;">${value.replace(/\n/g, "<br/>")}</p>`;
    } else if (Array.isArray(value)) {
      bodyHtml = `<ul style="font-size: 11pt; line-height: 1.6; margin-bottom: 12pt; color: #222;">${value
        .map((item) => `<li>${typeof item === "string" ? item : JSON.stringify(item)}</li>`)
        .join("")}</ul>`;
    } else if (value) {
      bodyHtml = `<pre style="font-size: 10pt; background: #f5f5f5; padding: 10pt; border: 1px solid #ddd;">${JSON.stringify(value, null, 2)}</pre>`;
    }

    sectionsHtml += `
      <div style="margin-bottom: 20pt;">
        <h3 style="font-size: 13pt; color: #1a365d; border-bottom: 1.5pt solid #1a365d; padding-bottom: 4pt; margin-bottom: 8pt; text-transform: uppercase;">
          ${heading}
        </h3>
        ${bodyHtml}
      </div>
    `;
  }

  const docHtml = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${report.title}</title>
      <style>
        body { font-family: 'Calibri', 'Times New Roman', serif; margin: 40pt; color: #111; }
        .header { text-align: center; margin-bottom: 30pt; border-bottom: 2pt solid #000; padding-bottom: 15pt; }
        .disclaimer { margin-top: 30pt; padding: 10pt; background: #fff8e1; border: 1px solid #ffe082; font-size: 9pt; color: #5d4037; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 style="font-size: 18pt; margin-bottom: 6pt; color: #0f172a;">JURISIVA AI LEGAL INTELLIGENCE</h1>
        <h2 style="font-size: 14pt; margin-top: 0; font-weight: normal; color: #334155;">${report.title}</h2>
        <p style="font-size: 10pt; color: #64748b; margin: 4pt 0;">Matter: ${caseName} | Date: ${dateStr}</p>
      </div>

      ${sectionsHtml}

      <div class="disclaimer">
        <strong>Confidential Legal Work Product:</strong> Generated by Jurisiva AI. This document is intended solely for professional legal review and analysis.
      </div>
    </body>
    </html>
  `;

  const fileName = `${sanitizeFileName(report.title || "Legal_Report")}_${Date.now()}.doc`;
  triggerBrowserDownload(docHtml, fileName, "application/msword");
}

/**
 * Export Legal Report as Formatted Text (.txt)
 */
export function downloadReportAsText(report: LegalReportData, caseName = "Case") {
  const dateStr = new Date().toLocaleString("en-IN");
  let text = `================================================================================
JURISIVA AI LEGAL DUE DILIGENCE & ASSESSMENT REPORT
================================================================================
TITLE:   ${report.title}
MATTER:  ${caseName}
DATE:    ${dateStr}
================================================================================\n\n`;

  for (const [section, value] of Object.entries(report.content || {})) {
    const heading = section.replace(/_/g, " ").toUpperCase();
    text += `--------------------------------------------------------------------------------\n`;
    text += `${heading}\n`;
    text += `--------------------------------------------------------------------------------\n`;

    if (typeof value === "string") {
      text += `${value}\n\n`;
    } else if (Array.isArray(value)) {
      value.forEach((item, i) => {
        text += `${i + 1}. ${typeof item === "string" ? item : JSON.stringify(item)}\n`;
      });
      text += `\n`;
    } else if (value) {
      text += `${JSON.stringify(value, null, 2)}\n\n`;
    }
  }

  text += `================================================================================
CONFIDENTIAL LEGAL WORK PRODUCT — JURISIVA AI LEGAL INTELLIGENCE
================================================================================\n`;

  const fileName = `${sanitizeFileName(report.title || "Legal_Report")}_${Date.now()}.txt`;
  triggerBrowserDownload(text, fileName, "text/plain;charset=utf-8");
}

/**
 * Open Chrome Print-to-PDF Window for high-resolution vector PDF printing/saving
 */
export function printReportAsPdf(report: LegalReportData, caseName = "Case") {
  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let sectionsHtml = "";
  for (const [section, value] of Object.entries(report.content || {})) {
    const heading = section.replace(/_/g, " ").toUpperCase();
    let bodyHtml = "";

    if (typeof value === "string") {
      bodyHtml = `<p style="font-size: 13px; line-height: 1.7; color: #1e293b; margin-bottom: 12px;">${value.replace(/\n/g, "<br/>")}</p>`;
    } else if (Array.isArray(value)) {
      bodyHtml = `<ul style="font-size: 13px; line-height: 1.7; color: #1e293b; padding-left: 20px; margin-bottom: 12px;">${value
        .map((item) => `<li>${typeof item === "string" ? item : JSON.stringify(item)}</li>`)
        .join("")}</ul>`;
    } else if (value) {
      bodyHtml = `<pre style="font-size: 11px; background: #f8fafc; padding: 12px; border-radius: 6px; border: 1px solid #e2e8f0; overflow-x: auto;">${JSON.stringify(value, null, 2)}</pre>`;
    }

    sectionsHtml += `
      <section style="margin-bottom: 24px; page-break-inside: avoid;">
        <h3 style="font-size: 14px; font-weight: 700; color: #1e40af; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">
          ${heading}
        </h3>
        ${bodyHtml}
      </section>
    `;
  }

  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to save/download PDF.");
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${report.title} — Jurisiva AI</title>
      <style>
        @page { size: A4; margin: 20mm 15mm 20mm 15mm; }
        body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; color: #0f172a; }
        .header { border-bottom: 3px solid #1e40af; padding-bottom: 16px; margin-bottom: 24px; }
        .logo { font-size: 20px; font-weight: 800; color: #1e40af; letter-spacing: 1px; }
        .title { font-size: 18px; font-weight: 700; color: #0f172a; margin: 10px 0 6px 0; }
        .meta { font-size: 12px; color: #64748b; }
        .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-align: center; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="background: #1e40af; color: white; padding: 12px 20px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; border-radius: 8px;">
        <span><strong>Jurisiva AI Report Ready:</strong> Click Print to save as PDF.</span>
        <button onclick="window.print()" style="background: white; color: #1e40af; border: none; padding: 8px 16px; border-radius: 6px; font-weight: bold; cursor: pointer;">Save / Print as PDF</button>
      </div>

      <div class="header">
        <div class="logo">⚖️ JURISIVA AI LEGAL INTELLIGENCE</div>
        <div class="title">${report.title}</div>
        <div class="meta">Matter: <strong>${caseName}</strong> · Certified Date: ${dateStr}</div>
      </div>

      ${sectionsHtml}

      <div class="footer">
        CONFIDENTIAL & PRIVILEGED LEGAL WORK PRODUCT · GROUNDED IN CERTIFIED CASE RECORDS · JURISIVA AI
      </div>

      <script>
        window.onload = function() {
          setTimeout(function() { window.print(); }, 400);
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

/**
 * Download Legal Draft (Pleading, Writ Petition, Legal Notice)
 */
export function downloadDraftFile(draft: { title: string; content: string; draft_type?: string }, format: "doc" | "txt" | "pdf") {
  const fileName = `${sanitizeFileName(draft.title || "Legal_Draft")}_v1`;

  if (format === "doc") {
    const html = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>${draft.title}</title>
      <style>body { font-family: 'Times New Roman', serif; margin: 40pt; font-size: 12pt; line-height: 1.8; color: #000; }</style>
      </head>
      <body>
        <h2 style="text-align: center; text-transform: uppercase;">${draft.title}</h2>
        <pre style="font-family: 'Times New Roman', serif; font-size: 12pt; white-space: pre-wrap; line-height: 1.8;">${draft.content}</pre>
      </body>
      </html>
    `;
    triggerBrowserDownload(html, `${fileName}.doc`, "application/msword");
    return;
  }

  if (format === "txt") {
    triggerBrowserDownload(draft.content, `${fileName}.txt`, "text/plain;charset=utf-8");
    return;
  }

  if (format === "pdf") {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>${draft.title}</title>
      <style>
        body { font-family: 'Times New Roman', Georgia, serif; margin: 40px; font-size: 13px; line-height: 1.8; color: #000; }
        @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
      </style>
      </head>
      <body>
        <h2 style="text-align: center; font-size: 16px; margin-bottom: 24px; text-transform: uppercase;">${draft.title}</h2>
        <pre style="font-family: inherit; font-size: 13px; white-space: pre-wrap; line-height: 1.8;">${draft.content}</pre>
        <script>window.onload = function() { setTimeout(function() { window.print(); }, 300); };</script>
      </body>
      </html>
    `);
    win.document.close();
  }
}
